name: add artifact links to pr
on:
  workflow_run:
    workflows: [Trigger Phrase Workflow]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    runs-on: [ubuntu-latest]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: add artifact links to pull request and related issues step
        uses: dpo/artifacts-url-comments@v0.0.2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "Here are the artifacts"
            format: "name"
            addTo: "pull"
